name: Qodana

on:
  push:
    branches:
      - main
      - dev

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.2
        env:
          QODANA_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiTHY5MXEiLCJvcmdhbml6YXRpb24iOiJMOXFObiIsInRva2VuIjoiZ2xXNHIiLCJ0b2tlbl90eXBlIjoicHJvamVjdCJ9.njcC71MVZhU97MGxQmXDlqwaKD0ZGS42DZxE2JDz_EU"
          QODANA_ENDPOINT: "https://qodana.cloud"
